name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Build
        run: go build -o dragonfly_exe -v .

      - name: Vet
        run: go vet ./...

      - name: Formatting
        run: test -z $(go fmt ./...)

      - name: Staticcheck
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          GOBIN=$PWD/bin go install honnef.co/go/tools/cmd/staticcheck
          ./bin/staticcheck ./...

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Build
        run: go build -o dragonfly_exe -v .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dragonfly_exe
          asset_name: dragonfly_exe.exe
          asset_content_type: application/exe

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: dragonfly_exe
          path: dragonfly_exe
